# Generated by Django 5.2.17 on 2026-09-26 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('lost', 'Perdido'), ('found', 'Encontrado')], max_length=10, verbose_name='tipo')),
                ('title', models.CharField(max_length=100, verbose_name='título')),
                ('description', models.TextField(help_text='Descreva o item e o ponto exato onde foi perdido ou encontrado (sala, andar etc.).', verbose_name='descrição')),
                ('category', models.CharField(choices=[('electronics', 'Eletrônicos'), ('documents', 'Documentos'), ('keys', 'Chaves'), ('wallets_bags', 'Carteiras e bolsas'), ('clothing', 'Roupas e acessórios'), ('school_supplies', 'Material escolar'), ('bottles', 'Garrafas e copos'), ('other', 'Outros')], max_length=20, verbose_name='categoria')),
                ('location', models.CharField(choices=[('icex', 'ICEx'), ('cad1', 'CAD 1'), ('cad2', 'CAD 2'), ('cad3', 'CAD 3'), ('engineering', 'Escola de Engenharia'), ('central_library', 'Biblioteca Central'), ('fafich', 'FAFICH'), ('letters', 'Faculdade de Letras'), ('restaurant', 'Restaurante Universitário'), ('services_square', 'Praça de Serviços'), ('sports_center', 'Centro Esportivo'), ('other', 'Outro')], max_length=20, verbose_name='local')),
                ('photo', models.ImageField(blank=True, upload_to='items/', verbose_name='foto')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('resolved', 'Resolvido')], default='open', max_length=10, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'itens',
                'ordering': ['-created_at'],
            },
        ),
    ]
