# Generated by Django 5.2.17 on 2026-09-26 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='occurred_on',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='data do ocorrido'),
        ),
        migrations.AddField(
            model_name='item',
            name='occurred_period',
            field=models.CharField(blank=True, choices=[(None, 'Não sei'), ('morning', 'Manhã'), ('afternoon', 'Tarde'), ('night', 'Noite')], max_length=10, verbose_name='turno'),
        ),
    ]
